### ISSUE TITLE
ReproHack paper 3: A multi-level analysis of data quality for formal software citation

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/AIM-ECR-network#31]
[ReproHack website link](https://www.reprohack.org/paper/86/)

Tools needed:
- R
- RStudio
- Quarto (quick to install if you don't have it already and very similar to R Markdown)

**Comment by BatoolMM** [comment]
Thank you @raniakous - I will close this issue since it is completed in ECR in-person event in London!
