### ISSUE TITLE
ReproHack website 4: Measuring the impact of COVID-19 vaccine misinformation on vaccination intent in the UK and USA

### ISSUE THREAD

**Issue by eirini-zormpa** [aim-rsf/AIM-ECR-network#32]
[ReproHack website link](https://www.reprohack.org/paper/75/)

Tools needed:
- Python
- Jupyter Notebooks

**Comment by RayStick** [comment]
I had a go at this one so please feel free to chat to me if you struggle with get going!

**Comment by raniakous** [comment]
pystan package take ages to get installed

**Comment by BatoolMM** [comment]
Thank you @raniakous - I will close this issue since it is completed in ECR in-person event in London!
