### ISSUE TITLE
ECR Representatives Meeting

### ISSUE THREAD

**Issue by BatoolMM** [aim-rsf/AIM-ECR-network#38]
# ECR Representatives Meeting Checklist

**Meeting Details:**
- **Date:** 24 Jan 2024
- **Time:** 11:00am

**Roles:**
- [x] **Facilitator:** @BatoolMM 
  - Responsible for guiding the meeting, ensuring all agenda items are covered, and managing time efficiently.
- [x] **Chair:** @EKaroune 
  - Leads the meeting, introduces agenda items, and ensures a smooth flow of discussion.
- [x] **Note-Taker:** @BatoolMM @EKaroune 
  - Takes detailed notes during the meeting, capturing key points, decisions, and action items.
- [x] **Follow-Up Coordinator:** @EKaroune
  - Follows up on action items and decisions made during the meeting.

**Pre-Meeting Checklist:**
- [x] Finalise and share the meeting agenda with all ECR representatives.
- [x] Confirm the meeting date, time, and virtual meeting link (if applicable).
- [x] Distribute any pre-meeting materials or information required for discussion.

**Meeting Checklist:**
- [x] Start the meeting on time.
- [x] Facilitator to welcome attendees and introduce the chair.
- [x] Chair to overview the agenda and set the tone for the meeting.
- [x] Discuss each agenda item, allowing time for questions and contributions from all representatives.
- [x] Note-Taker to capture discussion points, decisions, and action items.
- [x] Confirm action items and assign responsibilities.
- [x] Chair to conclude the meeting, summarising key outcomes and next steps.

**Post-Meeting Checklist:**
- [x] Share meeting notes with all ECR representatives and relevant stakeholders.
- [ ] Follow up on action items and ensure responsible parties are clear on their tasks.
- [x] Schedule the next meeting, if applicable.

**Comment by BatoolMM** [comment]
@EKaroune I added my notes here: https://hackmd.io/4lW5Aa1XSYiJzhUyAFVhtw?both

Few notes:
- Happy to create a new PR for the notes.
- I created an issue template for ECR reps prep and ECR lunchtime prep
- I re-ordered the repo and renamed it ECR network.
- I don't have the Hackmd for ECR lunchtime, feel free to add your slides and send it.I don't think I captured something more important than the what I added.
- Let me know if you would like me to send the follow-up!

Feel free to change anything!

**Comment by EKaroune** [comment]
@BatoolMM can you give me access to this repo please as I can't edit files at the moment

**Comment by BatoolMM** [comment]
What about now?

**Comment by EKaroune** [comment]
Thanks - all good now 🚀
