### ISSUE TITLE
March ECR Reps

### ISSUE THREAD

**Issue by BatoolMM** [aim-rsf/AIM-ECR-network#46]
# ECR Representatives Meeting Checklist

**Meeting Details:**
- **Date:** 27 March
- **Time:** 12:15
- **Agenda:** New ECR Application 

**Roles:**
- [x] **Facilitator:** _Assignee's Name_
  - Responsible for guiding the meeting, ensuring all agenda items are covered, and managing time efficiently.
- [x] **Chair:** _Assignee's Name_
  - Leads the meeting, introduces agenda items, and ensures a smooth flow of discussion.
- [x] **Note-Taker:** _Assignee's Name_
  - Takes detailed notes during the meeting, capturing key points, decisions, and action items.
- [x] **Follow-Up Coordinator:** _Assignee's Name_
  - Follows up on action items and decisions made during the meeting.

**Pre-Meeting Checklist:**
- [x] Finalise and share the meeting agenda with all ECR representatives.
- [x] Confirm the meeting date, time, and virtual meeting link (if applicable).
- [x] Distribute any pre-meeting materials or information required for discussion.

**Meeting Checklist:**
- [x] Start the meeting on time.
- [x] Facilitator to welcome attendees and introduce the chair.
- [x] Chair to overview the agenda and set the tone for the meeting.
- [x] Discuss each agenda item, allowing time for questions and contributions from all representatives.
- [x] Note-Taker to capture discussion points, decisions, and action items.
- [x] Confirm action items and assign responsibilities.
- [x] Chair to conclude the meeting, summarising key outcomes and next steps.

**Post-Meeting Checklist:**
- [x] Share meeting notes with all ECR representatives and relevant stakeholders.
- [x] Follow up on action items and ensure responsible parties are clear on their tasks.
- [x] Schedule the next meeting, if applicable.

**Comment by BatoolMM** [comment]
@EKaroune if we received an applications for ECR day tomorrow’s, would you be able to score it before your leave? Just asking because we might need to show the score and discuss the applications **programme** in the ECR reps meeting?

**Comment by EKaroune** [comment]
Yes I can get those done this friday or monday, tuesday next week

**Comment by BatoolMM** [comment]
Fingers crossed, we receive applications this week!

**Comment by BatoolMM** [comment]
I have added the notes to the repo - it can be closed!
